config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :fixes do
      resources :promotion_forms
      post 'build_promote'
    end
  end

  post '/users/:user_id/fixes/:fix_id/promotion_forms/:id/members/create', to: 'members#create', as: 'create_member'

  root to: 'fixes#index'
end

app/models/action_information.rb
class ActionInformation < ApplicationRecord
  belongs_to :fix
  belongs_to :from_level, class_name: 'Level'
  belongs_to :to_level, class_name: 'Level'
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/approve_information.rb
class ApproveInformation < ApplicationRecord
  belongs_to :fix
  belongs_to :from_level, class_name: 'Level'
  belongs_to :to_level, class_name: 'Level'
  belongs_to :user
end

app/models/fix.rb
class Fix < ApplicationRecord
  belongs_to :level
  has_many :promotion_forms, dependent: :destroy
  belongs_to :user

  enum status: { ww_development: 'WW Development',
                 uat_testing: 'UAT Testing',
                 e2e_testing: 'E2E Testing',
                 ready_for_prod: 'Ready for PROD' }

  def self.build_promote(fix)
    @new_level = Level.find(fix.level.id + 1)
    ActionInformation.create(fix: fix,
                             from_level: fix.level,
                             to_level: @new_level,
                             user: fix.user,
                             action: 'build and promote')
    fix.update_attribute(:level, @new_level)
  end
end

app/models/fix_number.rb
require 'singleton'

class FixNumber < ApplicationRecord

  @@instance = FixNumber.first

  def self.new
    update_number
    code
  end

  def self.update_number
    @@code = @@instance.number
    @@instance.number += 1
    @@instance.save
  end

  def self.code
    @@code
  end
end

app/models/interlink.rb
class Interlink < ApplicationRecord
  belongs_to :member
  belongs_to :first_promform, class_name: 'PromotionForm'
  belongs_to :second_promform, class_name: 'PromotionForm'
  belongs_to :level
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :from, class_name: 'ActionInformation', foreign_key: 'from_level_id'
  has_many :to, class_name: 'ActionInformation', foreign_key: 'to_level_id'
  has_many :member_locations
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :member_type
  belongs_to :promotion_form
end

app/models/member_location.rb
class MemberLocation < ApplicationRecord
  belongs_to :member_type
  belongs_to :level
end

app/models/member_type.rb
class MemberType < ApplicationRecord
  has_many :members
  has_many :member_locations
end

app/models/promotion_form.rb
class PromotionForm < ApplicationRecord
  belongs_to :fix
  belongs_to :level
  has_many :members
  has_many :first,  class_name: 'Interlink', foreign_key: 'first_promform_id'
  has_many :second, class_name: 'Interlink', foreign_key: 'second_promform_id'
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           polymorphic: true,
           optional: true


validates :resource_type,
          inclusion: { :in => Rolify.resource_types },
          allow_nil: true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :fixes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fixes_controller.rb
class FixesController < ApplicationController
  before_action :set_user, except: [:index]

  def index
    @fixes = Fix.all
  end

  def new
    @fix = Fix.new
    @fix.number = 'ADM'.concat(new_fix_number)
  end

  def create
    @fix = @user.fixes.new(fix_params)
    @fix.number = 'ADM'.concat(new_fix_number)
    @fix.level = Level.find(1)
    @fix.status = 'ww_development'
    @fix.save
    redirect_to root_path
  end

  def edit

  end

  def updateend

  def destroy

  end

  def show
    @fix = Fix.includes(promotion_forms: %i[members]).find(params[:id])
    @types = MemberType.all
  end

  def build_promote
    Fix.build_promote(@user.fixes.find(params[:fix_id]))
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def new_fix_number
    (Fix.last.number.delete('^0-9').to_i + 1).to_s
  end

  def fix_params
    params.require(:fix).permit(:description)
  end
end

app/controllers/promotion_forms_controller.rb
class PromotionFormsController < ApplicationController
  before_action :set_user_and_fix

  def new
    @form = PromotionForm.new
  end

  def create
    @form = @fix.promotion_forms.create(promform_params)
    @form.level = @fix.level
    if @form.save
      respond_to do |format|
        format.js
      end
    end

    # respond_to do |format|
    #   if @form.save
    #     format.html { redirect_to @form, notice: 'Form was successfully created.' }
    #     format.json { render action: 'show', status: :created, location: @form }
    #     # added:
    #     format.js   { render action: 'show', status: :created, location: @form }
    #   else
    #     format.html { render action: 'new' }
    #     format.json { render json: @form.errors, status: :unprocessable_entity }
    #     # added:
    #     format.js   { render json: @form.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def set_user_and_fix
    @user = User.find(params[:user_id])
    @fix  = Fix.find(params[:fix_id])
  end

  def promform_params
    params.require(:promotion_form).permit(:name, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fixes_helper.rb
module FixesHelper
end

app/helpers/promotion_forms_helper.rb
module PromotionFormsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "EasyFix", root_path, :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.username %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to t("layouts.application.navbar.log_out"), destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("layouts.application.navbar.log_in"), new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/fixes/_fix.html.erb
<div class="container" xmlns="http://www.w3.org/1999/html">
  <div class="col-md-8">
    <div class="row stylish-panel">
      <% @fixes.each do |fix| %>
        <div class="col-md-4 col-sm-4 col-xs-12"
             style='height:150px; cursor:pointer'
             onclick="window.location='<%= root_path %>'">
          <div>
            <div>
              <h3><%= fix.number %></h3>
              <p><%= fix.description %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/fixes/_fix_card.html.erb
<div class="container" xmlns="http://www.w3.org/1999/html">
  <div class="col-md-10">
    <div class="row stylish-panel">
      <% @fixes.each do |fix| %>
        <div class="col-md-4 col-sm-4 col-xs-12"
             style='height:300px; cursor:pointer'
             onclick="window.location='<%= user_fix_path(fix.user, fix) %>'">
          <div>
            <h3><%= fix.number %></h3>
            <p><%= fix.description.split(".").first %></p>
            <p><%= fix.level.name %>/<%= fix.level.test_level %></p>
            <p><%= fix.read_attribute_before_type_cast('status') %></p>
            <p>Created by: <%= fix.user.username %></p>
            <p>Created at: <%= fix.created_at %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/fixes/index.html.erb
<div class="container">
  <%= render partial: "fixes/fix_card" %>
</div>

app/views/fixes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h4 style="padding-bottom: 15px">Detailed information</h4>
      <div class="container">
        FIX NUMBER: <%= @fix.number %>
        <div class="fix-section-header">FIX STATUS</div>
        ADM status: <%= @fix.status_before_type_cast %>
        <div class="fix-section-header">DESCRIPTION</div>
        <%= @fix.description %>
        <div class="fix-section-header">PROMOTION FORMS</div>
        <ul class="nav nav-pills forms">
          <% @fix.promotion_forms.each do |form| %>
            <li><a data-toggle="pill" href="#<%= form.name %>"><%= form.name %></a></li>
          <% end %>
        </ul>
        <%= link_to "Build/promote", user_fix_build_promote_path(@user, @fix), method: :post, class: "btn btn-default" %>
        <%= link_to "New promotion form", '#new_promotion_form_modal', { 'data-toggle': 'modal', class: "btn btn-default" } %>
      </div>
    </div>
    <div class="col-md-4">
      <h4>History</h4>
    </div>
  </div>
</div>

<div class="tab-content forms" id="promotion_tabs">
  <%= render partial: @fix.promotion_forms, as: :form %>
</div>

<!-- Modal -->
<div class="modal fade" id="new_promotion_form_modal" tabindex="-1" role="dialog" aria-labelledby="promotionFormLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modalTitle" id="promotionFormLabel">New promotion form</h4>
      </div>
      <%= render 'promotion_forms/new_modal', modal: true %>
    </div>
  </div>
</div>

app/views/promotion_forms/_new_modal.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for([@user, @fix, @fix.promotion_forms.build], remote: remote, html: { role: :form, 'data-model' =>'form' }) do |f| %>
  <div class="modal-body">
    <div class="form-group">
      <%= f.label "Form name:", class: 'control-label' %>
      <%= f.text_field :name, class: 'form-control' %>
      <span class="help-block"></span>
    </div>

    <div class="form-group">
      <%= f.label "Description" %>
      <%= f.text_area :description, class: 'form-control' %>
      <span class="help-block"></span>
    </div>

    <div class="form-group">
      <%= f.label "Members" %>
      <table class="table" id="members_table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Type</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody></tbody>
      </table>
      <a type="button" onclick="addRow()" class="btn btn-default">Add row</a>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
    <div class="btn-group" role="group">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<script>
    function addRow() {
        let row = $('<tr>' +
            '<td><input type="text" class="form-control" /></td>' +
            '</tr>');

        let array = [];
        <% @types.each do |type| %>
          array.push('<%= type.name %>');
        <% end %>

        let arr = array.map(function (item, i) {
            return {val: i+1, text: item};
        });

        let select_div = $('<div>');

        let sel = $('<select>').addClass('form-control');
        $(arr).each(function () {
            sel.append($("<option>").attr('value', this.val).text(this.text));
        });

        let trash = $('<td><a class="link-remove-row"><span class=\'glyphicon glyphicon-trash\'></span></a></td>');

        trash.click(function (event) {
            $(event.currentTarget).closest("tr").remove();
        });

        select_div.append(sel);
        row.append($('<td>').append(select_div)).append(trash);

        $("#members_table tr:last").after(row);
    }
</script>

app/views/promotion_forms/_promotion_form.html.erb
<div class="tab-pane" id="<%= form.name %>">
  <% form.members.each do |member| %>
    <%= member.name %>: <%= member.member_type.name %>
  <% end %>
</div>

app/views/promotion_forms/create.js.erb
$("ul.forms").append("<li><a data-toggle=\"pill\" href=\"#<%= @form.name %>\"><%= @form.name %></a></li>");
$("#promotion_tabs").html("<%= escape_javascript render partial: @fix.promotion_forms.last, as: :form  %>");
$("textarea.form-control").val('');
$("input.form-control").val('');
$("#new_promotion_form_modal").modal('toggle');
$("#members_table").find("tr:gt(1)").remove();

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>